export const GET_SCORING_PENDING = 'GET_SCORING_PENDING';
export const GET_SCORING_SUCCESS = 'GET_SCORING_SUCCESS';
export const GET_REQUESTS_LIST = 'GET_REQUESTS_LIST';
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
